### ISSUE TITLE
命令建议压缩

### ISSUE THREAD

**Issue by jiuker** [maplestoria/redis-event#12]
1.全部解析成命令，确实准确性比较高，但是同样的ops有限，也就是全量RDB阶段很耗时。可以使用重新压缩成6版本的，然后可以使用restore命令，一次性批量恢复。
golang版本为
func createValueDump(t byte, val []byte) []byte {
	var b bytes.Buffer
	c := digest.New()
	w := io.MultiWriter(&b, c)
	w.Write([]byte{t})
	w.Write(val)
	binary.Write(w, binary.LittleEndian, uint16(ToVersion))
	binary.Write(w, binary.LittleEndian, c.Sum64())
	return b.Bytes()
}
将一个rdb段的有效意义字节转成 restore的 byte
具体可以看 https://github.com/alibaba/RedisShake 搜索这个函数createValueDump。

**Comment by maplestoria** [comment]
感谢建议。

不过，对于`redis-event`，我对它的定位是一个以replication协议接收redis事件的通用程序。所以，如果我把rdb中的每一对key-value，都序列化成restore命令的那种格式，就不符合我对它的定位了。

你可以看下我的另一个程序: [copy-redis](https://github.com/maplestoria/copy-redis),这个程序就是我基于`redis-event`开发的一个专门用于同步Redis数据的小工具，支持单点/sharding/cluster。

**Comment by jiuker** [comment]
但是你那个程序是依赖redis-event，所以ops还是上不去，因为我们的程序高ops，我也按照Redis-Shake使用rust改造了一番，能运行，但是消耗CPU差不多是golang版本的1.5到2倍，可能姿势不对。ops 3W+，golang 40%，rust50%~80%不定。不再执着rust能按着golang摩擦了～

**Comment by maplestoria** [comment]
考虑到你提出的这个建议，后面我应该会再改进一下copy-redis。
起初我做这个也是因为redis-shake当时并不满足我的需求😄

**Comment by maplestoria** [comment]
@jiuker 考虑到你提出的这个建议，后面我应该会再改进一下copy-redis。
起初我做这个也是因为redis-shake当时并不满足我的需求😄
